version: 2

models:
    - name: sales
      description: sales completed with the selling price, cost and margin
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
      columns:
          - name: orders_id
            description: PK - orders identification
            tests : 
            - not_null
          - name: products_id
            tests : 
            - not_null
          - name: qty
          - name: turnover
            tests : 
            - not_null
          - name: purchase_cost
            tests : 
            - not_null
          - name: margin